### PR TITLE
updated readme

### PR DESCRIPTION
**Pull request by sonali-singh97**
check my code

### CODE REVIEW

**Comment by gvsvarun** [comment]
fight coronavirus

Move these inline styles to a CSS class

**Comment by sonali-singh97** [comment]
Done

**Comment by gvsvarun** [comment]
Great, I will send you stage-1 and you can merge this PR and create a new branch for stage-1 and make changes only there

**Comment by sonali-singh97** [comment]
> Great, I will send you stage-1 and you can merge this PR and create a new branch for stage-1 and make changes only there
 Alright ,will do so.

**Pull request merged**
